name: Data Pipeline

on:
  schedule:
    - cron: "0 0 * * *" # ירוץ כל יום בחצות
  workflow_dispatch: # מאפשר הרצה ידנית

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create .env file
        run: |
          cd "data_software"
          cat << EOF > .env
          # Platform payout rates
          PLATFORM_PAYOUT_SPOTIFY=0.0024
          PLATFORM_PAYOUT_BEATPORT=1.25

          # Database settings
          DB_PATH=mvp.db
          DATABASE_URL=sqlite:///mvp.db

          # Prophet settings
          PROPHET_CHANGEPOINT_PRIOR_SCALE=0.05
          PROPHET_SEASONALITY_PRIOR_SCALE=10.0
          PROPHET_SEASONALITY_MODE=multiplicative
          PROPHET_HOLIDAYS_PRIOR_SCALE=10.0

          # XGBoost settings
          XGB_MAX_DEPTH=6
          XGB_LEARNING_RATE=0.1
          XGB_N_ESTIMATORS=100

          # LSTM settings
          LSTM_UNITS=50
          LSTM_DROPOUT=0.2
          LSTM_EPOCHS=100
          LSTM_BATCH_SIZE=32

          # Additional settings
          LOG_LEVEL=INFO
          LOG_FILE=app.log
          FORECAST_HORIZON=12
          TRAIN_TEST_SPLIT=0.8
          RANDOM_STATE=42
          EOF

      - name: Check required files
        run: |
          cd "Data Software"
          if [ ! -f ".env" ]; then
            echo "Error: .env file is missing"
            exit 1
          fi
          if [ ! -f "etl.py" ] || [ ! -f "run_forecast.py" ]; then
            echo "Error: Required Python files are missing"
            exit 1
          fi

      - name: Create required directories
        run: |
          cd "Data Software"
          mkdir -p models input output data_raw

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "Data Software/requirements.txt"

      - name: Backup existing data
        run: |
          cd "Data Software"
          timestamp=$(date +%Y%m%d_%H%M%S)
          mkdir -p backups
          if [ -f "streaming_data.db" ]; then
            cp streaming_data.db "backups/streaming_data_${timestamp}.db"
          fi
          if [ -d "models" ]; then
            tar -czf "backups/models_${timestamp}.tar.gz" models/
          fi

      - name: Run ETL
        run: |
          cd "Data Software"
          python etl.py

      - name: Run Forecast
        run: |
          cd "Data Software"
          python run_forecast.py

      - name: Commit and push if changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update data and forecasts [skip ci]" && git push)

      - name: Cleanup old backups
        run: |
          cd "Data Software/backups"
          find . -type f -mtime +7 -delete  # מחק גיבויים ישנים מ-7 ימים
