name: Data Pipeline

on:
  schedule:
    - cron: "0 0 * * *" # ירוץ כל יום בחצות
  workflow_dispatch: # מאפשר הרצה ידנית

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "Data Software/requirements.txt"

      - name: Run ETL
        run: |
          cd "Data Software"
          python etl.py

      - name: Run Forecast
        run: |
          cd "Data Software"
          python run_forecast.py

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update data and forecasts [skip ci]" && git push)
